export { default as Public } from './Public';
export { default as Login } from './login';
export { default as Signup } from './signup';
export { default as Home } from './home';
export { default as Product } from './product';
export { default as EditProduct } from './product/edit-product';
export { default as CreateProduct } from './product/create-product';
export { default as NotFound } from './[.404.]';
export { default as Category } from './category';
